name: Wake Up Koyeb
on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch:      # Allows you to test it manually
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: curl -I https://dizzy-chloette-bernat-fe1a7933.koyeb.app/
